[package]
name = "loadbalanced_actors"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "loadbalanced_actors"
path = "src/main.rs"

[dependencies]
ractor = "0.15"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
tokio-test = "0.4"
