name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, beta]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        cache: true

    - name: Check formatting
      run: cargo fmt --all -- --check
      if: matrix.rust == 'stable' && matrix.os == 'ubuntu-latest'

    - name: Run clippy
      run: cargo clippy -- -D warnings
      if: matrix.rust == 'stable'

    - name: Build
      shell: bash
      run: |
        cargo build --release --verbose
        # Determine OS name and rename binary with .ractor.{os} suffix
        OS_NAME=$(uname -s | tr '[:upper:]' '[:lower:]')
        PROJECT_NAME=$(grep '^name = ' Cargo.toml | head -1 | sed 's/name = "(.*)"/1/')
        BINARY="${PROJECT_NAME}.ractor.${OS_NAME}"
        if [ "$RUNNER_OS" = "Windows" ]; then
          cp target/release/${PROJECT_NAME}.exe ${BINARY}.exe || true
        else
          cp target/release/${PROJECT_NAME} ${BINARY} || true
        fi

    - name: Test
      run: cargo test --verbose

    - name: Run Demo Application
      shell: bash
      run: |
        # Determine binary name: {project}.ractor.{os}
        OS_NAME=$(uname -s | tr '[:upper:]' '[:lower:]')
        PROJECT_NAME=$(grep '^name = ' Cargo.toml | head -1 | sed 's/name = "(.*)"/1/')
        BINARY="${PROJECT_NAME}.ractor.${OS_NAME}"
        if [ "$RUNNER_OS" = "Windows" ]; then
          timeout 5 ./${BINARY}.exe || true
        else
          timeout 5 ./${BINARY} || true
        fi
