name: CAF (C++) Code Validation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'lib/actor_simulation/caf_generator.ex'
      - 'examples/caf_*/**'
      - 'scripts/generate_caf_examples.exs'
      - 'scripts/test_caf_demo.sh'
      - '.github/workflows/caf_validation.yml'
  pull_request:
    branches: [ main ]

jobs:
  validate-caf-examples:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
        example: [caf_pubsub, caf_pipeline, caf_burst, caf_loadbalanced]

    steps:
    - uses: actions/checkout@v4

    - name: Install build tools
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install cmake
        fi

    - name: Install Conan
      uses: conan-io/setup-conan@v1

    - name: Configure Conan profile
      run: |
        conan profile detect --force

    - name: Make test script executable
      run: chmod +x scripts/test_caf_demo.sh

    - name: Run CAF example with test script
      run: ./scripts/test_caf_demo.sh ${{ matrix.example }}

