name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test (Elixir ${{ matrix.elixir }} / OTP ${{ matrix.otp }})
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        elixir: ['1.14', '1.15', '1.16']
        otp: ['25', '26']
        exclude:
          - elixir: '1.14'
            otp: '26'
    
    env:
      MIX_ENV: test
      CI: true
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-
      
      - name: Install dependencies
        run: mix deps.get
      
      - name: Compile
        run: mix compile --warnings-as-errors
      
      - name: Run tests (exclude slow)
        run: |
          mix test --exclude slow --exclude omnetpp \
            --formatter JUnitFormatter \
            --formatter ExUnit.CLIFormatter \
            --slowest 10
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.elixir }}-${{ matrix.otp }}
          path: _build/test/lib/gen_server_virtual_time/test-junit-report.xml
      
      - name: Publish test report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '_build/test/lib/gen_server_virtual_time/test-junit-report.xml'
          check_name: 'Test Report (Elixir ${{ matrix.elixir }} / OTP ${{ matrix.otp }})'
          detailed_summary: true
          include_passed: true
      
      - name: Run slow tests
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: mix test --only slow --slowest 5
  
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.16'
          otp-version: '26'
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-coverage-${{ hashFiles('**/mix.lock') }}
      
      - name: Install dependencies
        run: mix deps.get
      
      - name: Run tests with coverage
        env:
          MIX_ENV: test
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mix coveralls.github --exclude slow --exclude omnetpp
  
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.16'
          otp-version: '26'
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-quality-${{ hashFiles('**/mix.lock') }}
      
      - name: Cache Dialyzer PLTs
        uses: actions/cache@v4
        with:
          path: priv/plts
          key: ${{ runner.os }}-dialyzer-1.16-26-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-dialyzer-1.16-26-
      
      - name: Install dependencies
        run: mix deps.get
      
      - name: Check formatting
        run: mix format --check-formatted
      
      - name: Run Credo
        run: mix credo --strict
        continue-on-error: true
      
      - name: Run Dialyzer
        run: mix dialyzer --format github
  
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.16'
          otp-version: '26'
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-docs-${{ hashFiles('**/mix.lock') }}
      
      - name: Install dependencies
        run: mix deps.get
      
      - name: Generate sequence diagrams
        run: mix test --only diagram_generation
      
      - name: Build documentation
        run: mix docs
      
      - name: Upload diagrams
        uses: actions/upload-artifact@v4
        with:
          name: sequence-diagrams
          path: test/output/*.html
      
      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: doc/
  
  generated-vlingo:
    name: Test Generated VLINGO XOOM Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.16'
          otp-version: '26'
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      
      - name: Install Elixir dependencies
        run: mix deps.get
      
      - name: Generate VLINGO sample project
        run: mix run scripts/generate_vlingo_sample.exs
      
      - name: Build VLINGO generated code
        working-directory: vlingo_loadbalanced_generated
        run: mvn clean compile
      
      - name: Run VLINGO tests
        working-directory: vlingo_loadbalanced_generated
        run: mvn test
      
      - name: Upload VLINGO test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: vlingo-test-results
          path: vlingo_loadbalanced_generated/target/surefire-reports/*.xml
  
  validate-generators:
    name: Validate All Generator Scripts
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.16'
          otp-version: '26'
      
      - name: Install dependencies
        run: mix deps.get
      
      - name: Run OMNeT++ generator script
        run: |
          mix run scripts/generate_omnetpp_examples.exs
          # Check that at least one file was generated
          if [ ! -f "examples/omnetpp_pubsub/PubSubNetwork.ned" ]; then
            echo "ERROR: OMNeT++ generator did not create expected files"
            exit 1
          fi
          echo "✓ OMNeT++ generator: OK"
      
      - name: Run CAF generator script
        run: |
          mix run scripts/generate_caf_examples.exs
          # Check that at least one file was generated
          if [ ! -f "examples/caf_pubsub/main.cpp" ]; then
            echo "ERROR: CAF generator did not create expected files"
            exit 1
          fi
          echo "✓ CAF generator: OK"
      
      - name: Run Pony generator script
        run: |
          mix run scripts/generate_pony_examples.exs
          # Check that at least one file was generated
          if [ ! -f "pony_loadbalanced_generated/main.pony" ]; then
            echo "ERROR: Pony generator did not create expected files"
            exit 1
          fi
          echo "✓ Pony generator: OK"
      
      - name: Run Phony generator script
        run: |
          mix run scripts/generate_phony_examples.exs
          # Check that at least one file was generated
          if [ ! -f "phony_burst_generated/main.go" ]; then
            echo "ERROR: Phony generator did not create expected files"
            exit 1
          fi
          echo "✓ Phony generator: OK"
      
      - name: Run VLINGO generator script
        run: |
          mix run scripts/generate_vlingo_sample.exs
          # Check that at least one file was generated
          if [ ! -f "vlingo_loadbalanced_generated/pom.xml" ]; then
            echo "ERROR: VLINGO generator did not create expected files"
            exit 1
          fi
          echo "✓ VLINGO generator: OK"
      
      - name: Summary
        run: |
          echo "================================================"
          echo "✅ All 5 generator scripts executed successfully"
          echo "================================================"
          echo "Generators validated:"
          echo "  ✓ OMNeT++ (C++ network simulation)"
          echo "  ✓ CAF (C++ actors)"
          echo "  ✓ Pony (capabilities-secure actors)"
          echo "  ✓ Phony (Go actors)"
          echo "  ✓ VLINGO XOOM (Java actors)"
          echo "================================================"