name: Phony (Go) Code Validation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'lib/actor_simulation/phony_generator.ex'
      - 'examples/phony_*/**'
      - 'scripts/generate_phony_examples.exs'
      - '.github/workflows/phony_validation.yml'
  pull_request:
    branches: [ main ]

jobs:
  validate-phony-examples:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.21', '1.22']
        example: [phony_pubsub, phony_pipeline, phony_burst, phony_loadbalanced]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        cache: false

    - name: Download dependencies
      working-directory: examples/${{ matrix.example }}
      run: |
        go mod download

    - name: Build
      working-directory: examples/${{ matrix.example }}
      run: |
        go build -v ./...

    - name: Test
      working-directory: examples/${{ matrix.example }}
      run: |
        go test -v ./...

    - name: Run application (with timeout)
      working-directory: examples/${{ matrix.example }}
      shell: bash
      run: |
        go build -o app .
        # Cross-platform timeout: use GNU timeout on Linux, gtimeout on macOS (via coreutils), or fallback
        if command -v timeout &> /dev/null; then
          timeout 5 ./app || true
        elif command -v gtimeout &> /dev/null; then
          gtimeout 5 ./app || true
        else
          # Fallback: run in background with kill after timeout
          ./app & 
          PID=$!
          sleep 5
          kill $PID 2>/dev/null || true
          wait $PID 2>/dev/null || true
        fi

