name: Phony (Go) Code Validation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'lib/actor_simulation/phony_generator.ex'
      - 'examples/phony_*/**'
      - 'scripts/generate_phony_examples.exs'
      - 'scripts/test_phony_demo.sh'
      - '.github/workflows/phony_validation.yml'
  pull_request:
    branches: [ main ]

jobs:
  validate-phony-examples:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.21', '1.22']
        example: [phony_pubsub, phony_pipeline, phony_burst, phony_loadbalanced]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        cache: false

    - name: Make test script executable (Unix)
      if: runner.os != 'Windows'
      run: chmod +x scripts/test_phony_demo.sh

    - name: Run Phony example with test script (Unix)
      if: runner.os != 'Windows'
      run: ./scripts/test_phony_demo.sh ${{ matrix.example }}

    - name: Run Phony example (Windows)
      if: runner.os == 'Windows'
      shell: bash
      working-directory: examples/${{ matrix.example }}
      run: |
        go mod download
        go build -v ./...
        go test -v ./...
        go build -o app.exe .
        timeout 5 ./app.exe || true

